import { Student } from './student';

export const STUDENTS: Student[] = [
  {
    id: 11,
    firstName: 'Dan',
    lastName: 'Nicholson',
    rank: 'godan',
    birthdate: '1982-05-09',
    email: 'danthekarateman@hotmail.com',
    phone: '',
  },
  {
    id: 12,
    firstName: 'Sabrina',
    lastName: 'Bliem',
    rank: 'shodan',
    birthdate: '1975-10-02',
    email: '',
    phone: '',
  },
  {
    id: 13,
    firstName: 'Connor',
    lastName: 'Doman',
    rank: 'nidan',
    birthdate: '1997-06-14',
    email: 'domanc@student.ubc.ca',
    phone: '',
  },
  {
    id: 14,
    firstName: 'Josh',
    lastName: 'Rychtowski',
    rank: 'shodan',
    birthdate: '2000-06-06',
    email: '',
    phone: '',
  },
  {
    id: 15,
    firstName: 'Kristina',
    lastName: 'Pham',
    rank: 'shodan',
    birthdate: '2001-12-02',
    email: '',
    phone: '',
  },
  {
    id: 16,
    firstName: 'Nicholas',
    lastName: 'Agagnier',
    rank: 'white belt',
    birthdate: '1997-09-25',
    email: '',
    phone: '',
  },
  {
    id: 17,
    firstName: 'Jesse',
    lastName: 'Enkamp',
    rank: 'sandan',
    birthdate: '1994-04-20',
    email: '',
    phone: '',
  },
  {
    id: 18,
    firstName: 'Damien',
    lastName: 'Quintero',
    rank: 'godan',
    birthdate: '1984-07-04',
    email: '',
    phone: '',
  },
];
